# fly.toml app configuration file generated for fairvotercvapp on 2025-05-10T10:21:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fairvotercvapp'
primary_region = 'sea'

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"
    
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
